name: json_theme_plus
description: A library to dynamically generate a ThemeData object from a JSON file or dynamic map object
homepage: https://github.com/zeshuaro/json_theme_plus
version: 6.6.6

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  json_class: ^3.0.1
  json_schema: ^5.2.0
  json_theme_annotation: ^1.0.3+6
  logging: ^1.3.0
  meta: ^1.12.0

dev_dependencies:
  build: 2.4.1
  build_runner: 2.4.13
  code_builder: 4.10.1
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  json_theme_codegen: 1.1.3
  recase: 4.1.0
  source_gen: 1.5.0
